# 张量
和 numpy 数组很相似。在后续的自动微分章节中，会使用张量进行优化。

In [1]:
import numpy as np
import torch

## 初始化张量
我们有多种方法来创建张量。比较简单的，可以使用数据创建。创建时系统会自动判断数据类型。

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

也可以从 np 数组创建。同样的，也很容易将 tensor 转化为 np 数组

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)


使用已有的张量创建

In [6]:
x_ones = torch.ones_like(x_data)
print(f"Ones tensor:\n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Rand tensor:\n{x_rand}\n")

Ones tensor:
tensor([[1, 1],
        [1, 1]])

Rand tensor:
tensor([[0.8773, 0.1006],
        [0.3350, 0.5993]])



注意这里使用 rand_like时需要指明数据类型。torch.float

通过随机或者常数创建。
我们可以通过 shape 来描述张量的维度。

In [ ]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"rand tensor:\n{rand_tensor}\n")
print(f"ones tensor:\n{ones_tensor}\n")
print(f"zeros tensor:\n{zeros_tensor}\n")

rand tensor:
tensor([[0.9928, 0.5077, 0.2338],
        [0.1916, 0.8339, 0.5121]])

ones tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



这一这里如果我们是使用torch.rand()，传入的是张量的形状,支持直接传入表示张量形状的元组，也支持将形状的数字挨个传入；相应的，如果我们使用的是torch.rand_like()传入的是要模仿的 tensor。输出的结果会继承输入 tensor 的形状，数据类型，设备等，但是不会继承值。

## 张量的属性
一个张量的属性包含了他的形状，数据类型以及存储设备类型

In [8]:
tensor = torch.rand(2, 3)

print(f"shape of tensor\n {tensor.shape}")
print(f"dtype of tensor\n {tensor.dtype}")
print(f"device of tensor\n {tensor.device}")

shape of tensor
 torch.Size([2, 3])
dtype of tensor
 torch.float32
device of tensor
 cpu


## 张量操作
张量可以进行算数，线性运算，矩阵运算等操作。
一般而言，张量运算在 cuda 上运行最快，其次 mps，最后 cpu。

In [9]:
device = (
    'cuda' if torch.cuda.is_available()
    else 'mps' if torch.backends.mps.is_available()
    else 'cpu'
    )

tensor = tensor.to(device)

切片和投影操作和 np 向量很相似

In [12]:
tensor = torch.ones(4, 4)
print(tensor)

first_row = tensor[0]
print(f"first_row:\n {first_row}")

first_column = tensor[:, 0]
print(f"first_column:\n {first_column}")

last_column = tensor[:, -1]
print(f"last_column:\n {last_column}")

tensor[:, 1] = 0
print(tensor)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
first_row:
 tensor([1., 1., 1., 1.])
first_column:
 tensor([1., 1., 1., 1.])
last_column:
 tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


我们同样可以对张量按照一定的维度进行拼接。

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
